baseurl = "http://xiaojiong.net/"
title = "Persistence"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Xiaojiong"
googleAnalytics = "UA-50430029-1"
disqusShortname = "XXX"

[Author]
    name = "xiaojiong"
    profile = "http://weibo.com/577500331"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "人生就像一场马拉松"
    description = "当你的才华还撑不起你的野心时，你就应该静下心来学习。"
    github = "https://github.com/mixiaojiong"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
